// Generated by CoffeeScript 1.3.3
(function() {
  var compress, decompress;

  decompress = function(data) {
    return data;
  };

  compress = function(data) {
    return data;
  };

  exports.compress = module.exports.compress = compress;

  exports.decompress = module.exports.decompress = decompress;

}).call(this);
