// Generated by CoffeeScript 1.3.3
(function() {
  var compress, decompress;

  decompress = function(data) {
    var concat, distance, frame, index, length, string, x, _i, _j, _ref;
    string = '';
    index = 0;
    while (index < data.length) {
      frame = data[index];
      index += 1;
      if (frame >= 1 && frame <= 8) {
        string += data.toString('utf8', index, index + frame);
        for (x = _i = 0, _ref = frame - 1; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
          string += String.fromCharCode(0xE0E0);
        }
        index += frame;
      } else if (frame < 128) {
        string += String.fromCharCode(frame);
      } else if (frame >= 192) {
        string += ' ' + String.fromCharCode(frame ^ 128);
      } else {
        concat = (frame << 8) | data[index];
        distance = (concat >> 3) & 0x07FF;
        length = (concat & 7) + 3;
        if (length < distance) {
          string += string.slice(-distance, length - distance);
        } else {
          for (x = _j = 0; 0 <= length ? _j < length : _j > length; x = 0 <= length ? ++_j : --_j) {
            string += string[string.length - distance];
          }
        }
        index += 1;
      }
    }
    string = string.replace(/\uE0E0/g, '');
    return string;
  };

  compress = function(data) {
    throw new Error("Palmdoc Compression not supported yet.");
  };

  exports.compress = module.exports.compress = compress;

  exports.decompress = module.exports.decompress = decompress;

}).call(this);
